/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 20 16:43:52 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DataOfSquare_ESTest extends DataOfSquare_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DataOfSquare dataOfSquare0 = new DataOfSquare(0);
      dataOfSquare0.C = null;
      // Undeclared exception!
      try { 
        dataOfSquare0.lightMeUp(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DataOfSquare", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DataOfSquare dataOfSquare0 = new DataOfSquare(0);
      // Undeclared exception!
      try { 
        dataOfSquare0.lightMeUp(2459);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 2459, Size: 3
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DataOfSquare dataOfSquare0 = new DataOfSquare(0);
      // Undeclared exception!
      try { 
        dataOfSquare0.lightMeUp((-1500));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DataOfSquare dataOfSquare0 = null;
      try {
        dataOfSquare0 = new DataOfSquare(2603);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 2603, Size: 3
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DataOfSquare dataOfSquare0 = null;
      try {
        dataOfSquare0 = new DataOfSquare((-1632));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DataOfSquare dataOfSquare0 = new DataOfSquare(0);
      dataOfSquare0.lightMeUp(0);
  }
}
