/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 20 16:45:08 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.event.KeyEvent;
import javax.swing.JColorChooser;
import javax.swing.JEditorPane;
import javax.swing.JTextPane;
import javax.swing.MenuElement;
import javax.swing.MenuSelectionManager;
import javax.swing.event.MenuKeyEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class KeyboardListener_ESTest extends KeyboardListener_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      KeyboardListener keyboardListener0 = new KeyboardListener();
      JColorChooser jColorChooser0 = new JColorChooser();
      MenuElement[] menuElementArray0 = new MenuElement[0];
      MenuSelectionManager menuSelectionManager0 = new MenuSelectionManager();
      ThreadsController.directionSnake = 40;
      MenuKeyEvent menuKeyEvent0 = new MenuKeyEvent(jColorChooser0, 40, 40, 40, 40, 'z', menuElementArray0, menuSelectionManager0);
      keyboardListener0.keyPressed(menuKeyEvent0);
      assertEquals(8704, menuKeyEvent0.getModifiersEx());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      KeyboardListener keyboardListener0 = new KeyboardListener();
      JTextPane jTextPane0 = new JTextPane();
      ThreadsController.directionSnake = 38;
      KeyEvent keyEvent0 = new KeyEvent(jTextPane0, 38, 38, (-973), 38, 'j');
      keyboardListener0.keyPressed(keyEvent0);
      assertEquals(38, keyEvent0.getKeyCode());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      KeyboardListener keyboardListener0 = new KeyboardListener();
      JEditorPane jEditorPane0 = new JEditorPane();
      KeyEvent keyEvent0 = new KeyEvent(jEditorPane0, 39, (-4256L), 4, 39, 'T');
      ThreadsController.directionSnake = 4;
      keyboardListener0.keyPressed(keyEvent0);
      assertFalse(keyEvent0.isControlDown());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      KeyboardListener keyboardListener0 = new KeyboardListener();
      // Undeclared exception!
      try { 
        keyboardListener0.keyPressed((KeyEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("KeyboardListener", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      KeyboardListener keyboardListener0 = new KeyboardListener();
      ThreadsController.directionSnake = 3;
      JColorChooser jColorChooser0 = new JColorChooser();
      MenuElement[] menuElementArray0 = new MenuElement[5];
      MenuSelectionManager menuSelectionManager0 = new MenuSelectionManager();
      MenuKeyEvent menuKeyEvent0 = new MenuKeyEvent(jColorChooser0, 40, 40, 40, 40, '|', menuElementArray0, menuSelectionManager0);
      keyboardListener0.keyPressed(menuKeyEvent0);
      assertEquals('|', menuKeyEvent0.getKeyChar());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      KeyboardListener keyboardListener0 = new KeyboardListener();
      ThreadsController.directionSnake = 1;
      JColorChooser jColorChooser0 = new JColorChooser();
      MenuElement[] menuElementArray0 = new MenuElement[0];
      MenuSelectionManager menuSelectionManager0 = MenuSelectionManager.defaultManager();
      MenuKeyEvent menuKeyEvent0 = new MenuKeyEvent(jColorChooser0, 37, 37, 37, 37, 'z', menuElementArray0, menuSelectionManager0);
      keyboardListener0.keyPressed(menuKeyEvent0);
      assertEquals(0, menuKeyEvent0.getKeyLocation());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      KeyboardListener keyboardListener0 = new KeyboardListener();
      JColorChooser jColorChooser0 = new JColorChooser();
      MenuElement[] menuElementArray0 = new MenuElement[0];
      MenuSelectionManager menuSelectionManager0 = MenuSelectionManager.defaultManager();
      MenuKeyEvent menuKeyEvent0 = new MenuKeyEvent(jColorChooser0, 3, 3, 3, 3, 'z', menuElementArray0, menuSelectionManager0);
      keyboardListener0.keyPressed(menuKeyEvent0);
      assertFalse(menuKeyEvent0.isAltGraphDown());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      KeyboardListener keyboardListener0 = new KeyboardListener();
      JColorChooser jColorChooser0 = new JColorChooser();
      MenuElement[] menuElementArray0 = new MenuElement[0];
      MenuSelectionManager menuSelectionManager0 = new MenuSelectionManager();
      MenuKeyEvent menuKeyEvent0 = new MenuKeyEvent(jColorChooser0, 40, 40, 40, 40, 'z', menuElementArray0, menuSelectionManager0);
      keyboardListener0.keyPressed(menuKeyEvent0);
      assertFalse(menuKeyEvent0.isConsumed());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      KeyboardListener keyboardListener0 = new KeyboardListener();
      JEditorPane jEditorPane0 = new JEditorPane();
      KeyEvent keyEvent0 = new KeyEvent(jEditorPane0, 39, 4, 4, 39, 'T');
      keyboardListener0.keyPressed(keyEvent0);
      assertEquals(4L, keyEvent0.getWhen());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      KeyboardListener keyboardListener0 = new KeyboardListener();
      JTextPane jTextPane0 = new JTextPane();
      KeyEvent keyEvent0 = new KeyEvent(jTextPane0, 38, 38, 38, 38, 'j');
      keyboardListener0.keyPressed(keyEvent0);
      assertTrue(keyEvent0.isMetaDown());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      KeyboardListener keyboardListener0 = new KeyboardListener();
      JColorChooser jColorChooser0 = new JColorChooser();
      MenuElement[] menuElementArray0 = new MenuElement[0];
      MenuSelectionManager menuSelectionManager0 = MenuSelectionManager.defaultManager();
      MenuKeyEvent menuKeyEvent0 = new MenuKeyEvent(jColorChooser0, 37, 37, 37, 37, 'z', menuElementArray0, menuSelectionManager0);
      keyboardListener0.keyPressed(menuKeyEvent0);
      assertFalse(menuKeyEvent0.isAltDown());
  }
}
