/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 20 16:46:35 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import java.awt.Color;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SquarePanel_ESTest extends SquarePanel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SquarePanel squarePanel0 = new SquarePanel((Color) null);
      squarePanel0.ChangeColor((Color) null);
      assertTrue(squarePanel0.getFocusTraversalKeysEnabled());
  }
}
