/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 20 16:47:56 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Tuple_ESTest extends Tuple_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Tuple tuple0 = new Tuple(2448, 472);
      tuple0.yf = 907;
      int int0 = tuple0.getYf();
      assertEquals(907, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Tuple tuple0 = new Tuple(2448, 472);
      tuple0.yf = 907;
      tuple0.yf = (-629);
      int int0 = tuple0.getYf();
      assertEquals((-629), int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Tuple tuple0 = new Tuple(1, 2003);
      tuple0.ChangeData(0, 0);
      int int0 = tuple0.getY();
      assertEquals(0, tuple0.y);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Tuple tuple0 = new Tuple((-1), 0);
      tuple0.y = (-640);
      int int0 = tuple0.getY();
      assertEquals((-640), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Tuple tuple0 = new Tuple(1, 2003);
      tuple0.xf = 2003;
      int int0 = tuple0.getXf();
      assertEquals(2003, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Tuple tuple0 = new Tuple(2448, 472);
      tuple0.xf = (-2818);
      int int0 = tuple0.getXf();
      assertEquals((-2818), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Tuple tuple0 = new Tuple(0, 0);
      int int0 = tuple0.getX();
      assertEquals(0, tuple0.y);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Tuple tuple0 = new Tuple(2448, 472);
      tuple0.x = (-1);
      int int0 = tuple0.getX();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Tuple tuple0 = new Tuple(2448, 472);
      int int0 = tuple0.getYf();
      assertEquals(472, tuple0.y);
      assertEquals(2448, tuple0.x);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Tuple tuple0 = new Tuple(2448, 472);
      int int0 = tuple0.getY();
      assertEquals(472, int0);
      assertEquals(2448, tuple0.x);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Tuple tuple0 = new Tuple(2448, 472);
      int int0 = tuple0.getX();
      assertEquals(2448, int0);
      assertEquals(472, tuple0.y);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Tuple tuple0 = new Tuple(1, 2003);
      int int0 = tuple0.getXf();
      assertEquals(2003, tuple0.y);
      assertEquals(1, tuple0.x);
      assertEquals(0, int0);
  }
}
